services:
  crushing-be:
    build:
      context: ./backend
    image: crushing-be
    container_name: crushing-be
    restart: always
    env_file:
      - ./backend/.env
    networks:
      - nginx-public
      - henkaten-be_app-network
    volumes:
      - be_uploads:/app/uploads

  crushing-fe:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    image: crushing-fe
    container_name: crushing-fe
    restart: always
    networks:
      - nginx-public

networks:
  nginx-public:
    external: true
  henkaten-be_app-network:
    external: true

volumes:
  be_uploads:
    driver: local
